import libs = liboneapi-mkl%libs{mkl-rt}

for t : cxx{* -mkl-cluster-* -mkl-sycl -mkl-thread-gnu -mkl-thread-intel}
{
  n = $name($t)
  ./: exe{test-$n}: $t $libs
}

# thread tests
#
import thread_intel = liboneapi-mkl%libs{mkl-thread-intel}
exe{test-mkl-thread-intel}: cxx{mkl-thread-intel} $libs $thread_intel

import thread_gnu = liboneapi-mkl%libs{mkl-thread-gnu}
exe{test-mkl-thread-gnu}: cxx{mkl-thread-gnu} $libs $thread_gnu
./: exe{test-mkl-thread-gnu}: include = ($cc.target.class == 'linux')

# cluster tests
#
import cluster_lp64 = liboneapi-mkl%libs{mkl-cluster-lp64-intelmpi}
exe{test-mkl-cluster-lp64}: cxx{mkl-cluster-lp64} $libs $cluster_lp64
import cluster_ilp64 = liboneapi-mkl%libs{mkl-cluster-ilp64-intelmpi}
exe{test-mkl-cluster-ilp64}: cxx{mkl-cluster-ilp64} $libs $cluster_ilp64

# sycl tests
#
import sycl = liboneapi-mkl%libs{mkl-sycl}
exe{test-mkl-sycl}: cxx{mkl-sycl} $libs $sycl

# Disable until intel-mpi (liboneapi-mpi) etc. has been packaged.
#
./: exe{test-mkl-cluster-lp64}:  include = false
./: exe{test-mkl-cluster-ilp64}: include = false
./: exe{test-mkl-sycl}: include = false
