import libs = liboneapi-openmp%libs{openmp-rt}

for t : cxx{* -openmp-omptarget}
{
  n = $name($t)
  ./: exe{test-$n}: $t $libs
}

import omptarget = liboneapi-openmp%libs{openmp-omptarget}
exe{test-openmp-omptarget}: cxx{openmp-omptarget} $omptarget

# Requires intel.oneapi.lin.compilers-common.runtime (libimf, libsvml, libirng,
# libintlc) and intel.oneapi.lin.dpcpp-cpp-common.runtime (libsycl, libur_loader)
# - neither packaged yet.
#
./: exe{test-openmp-omptarget}: include = false
